package club.theexperiment.diex;

public class dPreset extends Die {
    //Creates a member of die class and sets number of sides
    public dPreset(int s) {
        setSides(s);
        /*
        if(s==2){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        if(s==4){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        if(s==6){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.d6_1),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        if(s==8){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        if(s==10){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        if(s==12){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        if(s==20){this.setUriList({Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.),Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.)});}
        */
    }

}
